blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('<str:slug>/', views.post_detail, name="post-detail"),
    path('tags/<str:slug>/', views.tag_detail, name="tag-detail"),
]

devblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Tag(models.Model):
    """Model representing a tag for a blog post."""
    name = models.CharField(max_length=200, help_text='Enter a tag for a blog post (e.g. Django, Laravel, Docker, etc.)')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this tag."""
        return reverse('tag-detail', args=[str(self.slug)])


class Post(models.Model):
    """Model representing a blog post."""
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    slug = models.SlugField(unique=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    # a Post can have many Tags, and a Tag can have many Posts
    tags = models.ManyToManyField(Tag, help_text='Select tags for this post')

    class Meta:
        ordering = ['-published_date']

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this post."""
        return reverse('post-detail', args=[str(self.slug)])

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from blog.models import Post, Tag

def index(request):
    posts = Post.objects.all()

    return render(request, 'index.html', {
        'posts': posts
    })


def about(request):
    return render(request, 'about.html')


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    return render(request, 'post_detail.html', {
        'post': post
    })


def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug=slug)

    return render(request, 'tag_detail.html', {
        'tag': tag
    })

blog/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>
        dj knox - about
    </title>
{% endblock %}

{% block content %}
    <div class="about-container">
        <h1 class="about-heading">About Me</h1>
        <img class="about-img" src="{% static 'img/djknox.JPG' %}"/>
        <div class="about-text">
            I'm dj, a full-stack web developer based in Durham, North Carolina.
        </div>
        <div class="about-social-container">
            <div>
                Here's where to find me:
            </div>
            <div class="about-social-link-container">
                <div class="about-social-link-item">
                    <a href="https://github.com/djknox" target="_blank">github</a>
                </div>
                <div class="about-social-link-item">
                    <a href="https://linkedin.com/in/djknox" target="_blank">linkedin</a>
                </div>
                <div class="about-social-link-item">
                    <a href="https://twitter.com/danhknox" target="_blank">twitter</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}<title>freeshelf</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Caption&display=swap" rel="stylesheet">
  </head>
  <body>
      <header>
            <nav class="header-nav">
                <div class="nav-link-home">
                    <a href="{% url 'index' %}">dj knox</a>
                </div>
                <div class="nav-link-pages">
                    <a href="{% url 'about' %}">about</a>
                </div>
            </nav>
      </header>
      <div class="content">

        {% block content %}{% endblock %}

      </div>
      <footer>
            <nav class="footer-nav">
                <div class="nav-link-home">
                    <a href="{% url 'index' %}">dj knox</a>
                </div>
                <div class="nav-link-pages">
                    <a href="{% url 'about' %}">about</a>
                </div>
            </nav>
      </footer>
  </body>
</html>

blog/templates/index.html
{% extends "base.html" %}

{% block title %}
    <title>dj knox - web developer</title>
{% endblock %}

{% block content %}
    <div class="index-post-container">
        {% for post in posts %}
            <div class="index-post-item">
                <div class="index-post-link">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </div>
                <div class="index-post-date">
                    {{ post.published_date.date }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/post_detail.html
{% extends "base.html" %}

{% block title %}
    <title>
        dj knox - {{ post.title }}
    </title>
{% endblock %}

{% block content %}
    <div class="post-detail-container">
        <h1 class="post-detail-title">{{ post.title }}</h1>
        <h2 class="post-detail-date">{{ post.published_date.date }}</h2>
        <div class="post-detail-text">
            {{ post.text }}
        </div>
        <div class="post-detail-tag-container">
            {% for tag in post.tags.all %}
                <div class="post-detail-tag-item">
                    <a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/tag_detail.html
{% extends "base.html" %}

{% block title %}
    <title>
        {{ tag.name }}
    </title>
{% endblock %}

{% block content %}
    <div class="tag-detail-container">
        <h1 class="tag-detail-name">Posts about {{ tag.name }}</h1>
        <div class="tag-detail-post-container">
            {% for post in tag.post_set.all %}
                <div class="tag-detail-post-item">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}